<?php
	define('FPDF_FONTPATH', 'fpdf/font/');
	require_once('fpdf/fpdf.php');
	include_once("DBManager.php");

	$objCon = new DBManager;

	class PDF extends FPDF
	{
		var $widths;
		var $aligns;

		function Header()
		{
			$this->SetFont('helvetica', '', 10);
			//$this->Text(20,14,'Historial clinico',0,'C', 0);
			$this->Ln(30);
		}

		function Footer()
		{
			$this->SetY(-20);
			$this->SetFont('helvetica', 'B', 8);
			//$this->Cell(100,10,'Historial medico',0,0,'L');
		}
	}

	/*$id_Folio=7;*/

	if ($objCon->conectar()==true)
	{
		
		/* Revisa en la base de datos la cantidad de registros de NCPR's */
		$sql0="SELECT COUNT(*) FROM tbncprs";
		$result0=mysql_query($sql0) or die;

		/* Al número obtenido, se le suma 1 y se le asigna al NCPR */
		$id_Folio=(mysql_result($result0, 0));

		$sql="SELECT * FROM tbncprs WHERE id_Folio='$id_Folio'";
		$result = mysql_query($sql);
		
		while ($row=mysql_fetch_array($result)) 
		{ 
			$ORDEN=$row['Numero_Orden'];
			$PARTE=$row['Numero_Parte'];
			$TURNO=$row['Turno'];
			$FECHAENVIO=$row['Fecha_Envio'];
			$DESCRIPCIONPARTE=$row['Descripcion_Producto'];
			$PROVEEDOR=$row['Nombre_Proveedor'];
			$REPORTA=$row['Reportado_Por'];
			$GENERA=$row['Generado_Por'];
			$FECHA=$row['Fecha'];
			$HORA=$row['Hora'];
			$area_falla_detectada=$row['Origen_Falla_Detectada'];
			$LOCALIZADEFECTO=$row['Origen_Falla_Detectada'];
			$LOCALIZADEFECTODESC=$row['Origen_Falla_Descripcion'];
			$LOCACIONDEFECTO=$row['Locacion_Falla'];
			$LOCACIONDEFECTODESC=$row['Locacion_Falla_Desc'];
			$PIEZASORDEN=$row['Numero_Piezas'];
			$PIEZASRECHAZADAS=$row['Numero_Piezas_Rechazadas'];
			$RECHAZO=$row['Razon_Rechazo'];
			$DESCRIPCIONFALLA=$row['Descripcion'];
			$DISPOSICION=$row['Disposicion_Producto'];
			$DISPOSICIONDESCRIPCION=$row['Disposicion_Producto_Desc'];
			$RECHAZODESCRIPCION=$row['Razon_Rechazo_Desc'];	
			$DETECCION=$row["Area_Dept_Codigo"];
			$DETECCIONDESCRIPCION=$row["Area_Dept_Desc"];
		}
	}
	
	$DISPOSICIONPD=$DISPOSICION .' - '. $DISPOSICIONDESCRIPCION;
	$LOCALIZADD=$LOCALIZADEFECTO .' - '. $LOCALIZADEFECTODESC;
	$LOCACIONFD=$LOCACIONDEFECTO .' - '. $LOCACIONDEFECTODESC;
	$RECHAZOD=$RECHAZO .' - '. $RECHAZODESCRIPCION;
	$DETEC=$DETECCION .' - '. $DETECCIONDESCRIPCION;

	/* Declaración de variables */
	//$folio=$_POST['id_folio'];Generado por (Generated by):
	$documento_no="VL-PA-SGC-001-F02";
	$pagina="1 OF 1";
	$document="NON-CONFORMING PRODUCT REPORT";
	$revision="4";
	$fecha=$FECHA;
	$nombre_documento="NON-CONFORMING PRODUCT REPORT (ENGLISH)";
	
	//$foto1="img/foto1.jpg";
	//$foto2="img/foto2.jpg";Generado por (Generated by):
	//$foto3="img/foto3.jpg";
	/* Fin de declaración de variables */

	/* Variables del sistema*/
	$setx=13;
	$cellx=45;
	$cellsize=194;
	$setderecha=99;
	
	$x=4;
	$y=202;
	$c=4;
	/* Fin de variables del sistema*/

	// PDF(Vertical, Milimetros, Tamaño Carta)
	$pdf=new PDF('P', 'mm', 'Letter');
	$pdf->AddPage();
	$pdf->SetFont('helvetica', '', '8');
	
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(2, 2, 206, 265);   // Contenedor principal
	
	//Tabla1
	$t1=4;
	
	$pdf->Image('./img/Logo.jpg', 8, $t1+1, 50); //Imagen de logotipo
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	
	$pdf->Rect($x, $t1, $y, 10);  
	$pdf->Rect($x, $t1+10, $y, 10); 
	
	$pdf->Line(88, $t1, 88, $t1+20);
	$pdf->Line(158, $t1, 158, $t1+10);
	
	
	$pdf->SetXY($x+90, $t1+3);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(30, 5, "DOCUMENTO NO.:   VL-PA-SGC-001-F12", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+160, $t1+3);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(1, 5, "PAGINA: 1 OF 1", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+4, $t1+12);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(1, 0, "DOCUMENT: DEVIATION REQUEST", 0, 1, 'L', 'F');

	$pdf->SetXY($x+4, $t1+15);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(1, 0, "REVISION: 4", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+4, $t1+18);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(1, 0, "FECHA: 12/10/2016", 0, 1, 'L', 'F');

	$pdf->SetXY($x+85, $t1+13.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(1, 5, "NOMBRE DEL DOCUMENTO:    PETICION DE DESVIACION", 0, 1, 'L', 'F');

	
	
	//Tabla2
	$t2=25;
	
	$pdf->SetXY($x, $t2);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(40, 4, "Deviation No. (No. Desviacion):", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+40, $t2);
	$pdf->SetFont('Arial', '', '8');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Cell(10, 5, "XXXX", 0, 1, 'L','F');
	
	$pdf->SetXY($x+60, $t2);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(40, 4, "Required by (Requerida por):", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+100, $t2);
	$pdf->SetFont('Arial', '', '8');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Cell(10, 5, "xxxxxxxxxxxxxxxxxxxxxxxxx", 0, 1, 'L','F');
	
	$pdf->SetXY($x+148, $t2);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(18, 4, "  Date (Fecha):", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+166, $t2);
	$pdf->SetFont('Arial', '', '8');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Cell(10, 5, "xxxxxxxxxxxx", 0, 1, 'L','F');
	
	$pdf->SetXY($x, $t2+4);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); 
	$pdf->cell(0, 4, "Affected parts (Partes afectadas)", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x, $t2+8);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Blanco
	$pdf->cell(83, 4, "Specification P/N to be replaced (Especificacion N/P a reemplazarse)", 0, 1, 'L', 'F');
		
	$pdf->SetXY($x+85, $t2+8);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Cell(30, 5, "XXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'C');
	
	$pdf->SetXY($x, $t2+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Blanco
	$pdf->cell(33, 4, "Description (Descripcion)", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+35, $t2+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255,255,255); // Color Blanco
	$pdf->cell(40, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t2+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Blanco
	$pdf->cell(65, 4, "Deviation P/N to be used (Desviacion N/P a utilizarse)", 0, 1, 'L', 'F');
		
	$pdf->SetXY($x+67, $t2+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Cell(30, 5, "XXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'C');
	
	$pdf->SetXY($x, $t2+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Blanco
	$pdf->cell(33, 4, "Description (Descripcion)", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+35, $t2+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255,255,255); // Color Blanco
	$pdf->cell(30, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	
	
	$pdf->Rect($x, $t2, $y, $c);  
	$pdf->Rect($x, $t2+$c, $y, $c);
	$pdf->Rect($x, $t2+$c*2, $y, $c);
	$pdf->Rect($x, $t2+$c*3, $y, $c);
	$pdf->Rect($x, $t2+$c*4, $y, $c);
	$pdf->Rect($x, $t2+$c*5, $y, $c);
	$pdf->Line(44, $t2, 44, $t2+4);
	$pdf->Line(64, $t2, 64, $t2+4);
	$pdf->Line(104, $t2, 104, $t2+4);
	$pdf->Line(152, $t2, 152, $t2+4);
	$pdf->Line(170, $t2, 170, $t2+4);
	$pdf->Line(87, $t2+8, 87, $t2+12);
	$pdf->Line(37, $t2+12, 37, $t2+16);
	$pdf->Line(69, $t2+16, 69, $t2+20);
	$pdf->Line(37, $t2+20, 37, $t2+24);
	
	//Tabla3
	$t3=50;
	
	$pdf->SetXY($x, $t3);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(18, 4, "SO#", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+18, $t3);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(103, 4, "Part Name", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+120, $t3);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(60, 4, "Job Affected", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+180, $t3);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(22, 4, "Quantity", 0, 1, 'C', 'F');
	
	
	
	$pdf->SetXY($x, $t3+4);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+4);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+4);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+4);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');

	
	
	$pdf->SetXY($x, $t3+8);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+8);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+8);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+8);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');

	$pdf->SetXY($x, $t3+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+24);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+24);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+24);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+24);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+28);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+28);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+28);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+28);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+44);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+44);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+44);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+44);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+60);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+60);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+60);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+60);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+64);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+64);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+64);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+64);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+68);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+68);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+68);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+68);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+72);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+72);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+72);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+72);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+76);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+76);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+76);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+76);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x, $t3+80);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(18, 4, "XXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+18, $t3+80);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(103, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+120, $t3+80);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(70, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'L', 'F');
	
	$pdf->SetXY($x+185, $t3+80);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetTextColor(0, 51, 102); // Color AZUL
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(17, 4, "XXXXX", 0, 1, 'L', 'F');
	
	
	$pdf->Rect($x, $t3, $y, $c);  
	$pdf->Rect($x, $t3+$c, $y, $c);  
	$pdf->Rect($x, $t3+$c*2, $y, $c);  
	$pdf->Rect($x, $t3+$c*3, $y, $c);  
	$pdf->Rect($x, $t3+$c*4, $y, $c);  
	$pdf->Rect($x, $t3+$c*5, $y, $c);  
	$pdf->Rect($x, $t3+$c*6, $y, $c);  
	$pdf->Rect($x, $t3+$c*7, $y, $c);  
	$pdf->Rect($x, $t3+$c*8, $y, $c);  
	$pdf->Rect($x, $t3+$c*9, $y, $c);  
	$pdf->Rect($x, $t3+$c*10, $y, $c);  
	$pdf->Rect($x, $t3+$c*11, $y, $c);  
	$pdf->Rect($x, $t3+$c*12, $y, $c);  
	$pdf->Rect($x, $t3+$c*13, $y, $c);  
	$pdf->Rect($x, $t3+$c*14, $y, $c);  
	$pdf->Rect($x, $t3+$c*15, $y, $c);  
	$pdf->Rect($x, $t3+$c*16, $y, $c);  
	$pdf->Rect($x, $t3+$c*17, $y, $c);  
	$pdf->Rect($x, $t3+$c*18, $y, $c);  
	$pdf->Rect($x, $t3+$c*19, $y, $c);  
	$pdf->Rect($x, $t3+$c*20, $y, $c);  
	
	
	$pdf->Line(22, $t3, 22, $t3+84);
	$pdf->Line(123, $t3, 123, $t3+84);
	$pdf->Line(188, $t3, 188, $t3+84);
	


	//Tabla4
	$t4=135;
	
	$pdf->SetXY($x, $t4);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(0, 4, "Archivo fotografico (Photo Archive)", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x,$t4+4);
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(66, 56, utf8_decode(""), 1, 1, 'C');

	$pdf->SetXY($x+66, $t4+4);
	// C (Centra el texto de la celda)
	$pdf->Multicell(71, 56, utf8_decode(""), 1, 1, 'C');

	$pdf->SetXY($x+137, $t4+4);
	// C (Centra el texto de la celda)
	$pdf->Multicell(65, 56, utf8_decode(""), 1, 1, 'C');
	
	$pdf->Rect($x, $t4, $y, $c);  
	
	//Tabla5
	$t5=196;

	$pdf->SetXY($x, $t5);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(60, 4, "Description of change (Descripcion del cambio)", 0, 1, 'C', 'F');

	$pdf->SetXY($x+62, $t5);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(0, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x, $t5+4);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(0, 4, "Reason for change (Razon del cambio)", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x, $t5+8);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(0, 4, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x, $t5+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(50, 4, "Validated by Sustaining Engineering", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+52, $t5+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(40, 4, "XXXXXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'C', 'F');
	
	$pdf->SetXY($x+104, $t5+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(58, 4, "Validated by Quality Engineering", 0, 1, 'C', 'F');	

	$pdf->SetXY($x+170, $t5+12);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "XXXXXXXXXXXXXXXXXXXXXX", 0, 1, 'C', 'F');
	
	
	$pdf->SetXY($x, $t5+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(50, 4, "Expiration date (Fecha de expiracion)", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+52, $t5+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "XX/XX/XXXX", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(58, 4, "Quantity to be produced (Cantidad a producirse)", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+16);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "XXXX", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x, $t5+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(50, 4, "Status", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+52, $t5+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "XXXXXXXXXX", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(58, 4, "By request of (Por peticion de)", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+20);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "XXXXXXXXXXXXXXXXXXXX", 0, 1, 'C', 'F');	
	
	
	$pdf->SetXY($x, $t5+24);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(104, 4, "Corrective action required? (Requiere accion correctiva?)", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+24);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255,255,255); // Color Azul
	$pdf->cell(90, 4, "XX", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x, $t5+28);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(0, 4, "Approval signatures (Firmas de aprobacion)", 0, 1, 'C', 'F');

	$pdf->SetXY($x, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "Quality & Eng.", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+52, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "Production", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(58, 4, "Materials", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "Plant manager", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+24);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255,255,255); // Color Azul
	$pdf->cell(90, 4, "XX", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x, $t5+28);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(0, 4, "Approval signatures (Firmas de aprobacion)", 0, 1, 'C', 'F');

	$pdf->SetXY($x, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "Quality & Eng.", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+52, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "Production", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(58, 4, "Materials", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+32);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "Plant manager", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x, $t5+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "	Calidad e Ing. Mexico", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+52, $t5+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "Produccion Mexico", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(58, 4, "Materiales Mexico", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+36);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "Gerente de planta Mexico", 0, 1, 'C', 'F');		
	
	$pdf->SetXY($x, $t5+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "X", 0, 1, 'C', 'F');	

	$pdf->SetXY($x+52, $t5+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "X", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(58, 4, "X", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+40);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "X", 0, 1, 'C', 'F');	
	
	
	$pdf->SetXY($x, $t5+44);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	$pdf->cell(0, 4, "Additional approval signatures (Firmas adicionales de aprobacion)", 0, 1, 'C', 'F');


	$pdf->SetXY($x, $t5+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "VP Operations", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+52, $t5+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "Customer Service RD", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(58, 4, "Engineering RD", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+48);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "Materials RD", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x, $t5+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "VP de operaciones", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+52, $t5+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "Servicio al cliente RD", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+104, $t5+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(58, 4, "Ingenieria RD", 0, 1, 'C', 'F');	
	
	$pdf->SetXY($x+170, $t5+52);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "Materiales RD", 0, 1, 'C', 'F');			
	
	$pdf->SetXY($x, $t5+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "X", 0, 1, 'C', 'F');	

	$pdf->SetXY($x+52, $t5+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(50, 4, "X", 0, 1, 'C', 'F');

	$pdf->SetXY($x+104, $t5+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(58, 4, "X", 0, 1, 'C', 'F');		
	
	$pdf->SetXY($x+170, $t5+56);
	$pdf->SetFont('Arial', 'B', '7');
	$pdf->SetFillColor(255, 255, 255); // Color Azul
	$pdf->cell(25, 4, "X", 0, 1, 'C', 'F');
	
	$pdf->Rect($x, $t5, $y, $c);  
	$pdf->Rect($x, $t5+$c, $y, $c);  
	$pdf->Rect($x, $t5+$c*2, $y, $c);  
	$pdf->Rect($x, $t5+$c*3, $y, $c);  
	$pdf->Rect($x, $t5+$c*4, $y, $c);  
	$pdf->Rect($x, $t5+$c*5, $y, $c);  
	$pdf->Rect($x, $t5+$c*6, $y, $c);  
	$pdf->Rect($x, $t5+$c*7, $y, $c);  
	$pdf->Rect($x, $t5+$c*8, $y, $c+4);  
	
	$pdf->Rect($x, $t5+$c*10, $y, $c);  
	$pdf->Rect($x, $t5+$c*11, $y, $c);  
	$pdf->Rect($x, $t5+$c*12, $y, $c+4);  
	
	$pdf->Rect($x, $t5+$c*14, $y, $c);  

	
	
	$pdf->Line(64, $t5, 64, $t5+4);
	$pdf->Line(54, $t5+12, 54, $t5+24);
	$pdf->Line(108, $t5+12, 108, $t5+28);
	$pdf->Line(166, $t5+12, 166, $t5+24);
	
	$pdf->Line(54, $t5+32, 54, $t5+44);
	$pdf->Line(108, $t5+32, 108, $t5+44);
	$pdf->Line(166, $t5+32, 166, $t5+44);

	$pdf->Line(54, $t5+48, 54, $t5+56);
	$pdf->Line(108, $t5+48, 108, $t5+56);
	$pdf->Line(166, $t5+48, 166, $t5+56);
	
	
	
	$pdf->SetXY(5, 255);
	$pdf->SetFont('Arial', 'B', '5.5');
	$pdf->SetFillColor(255, 255, 255); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell(0, 4, utf8_decode("2016 Visionaire Lighting. This document was created for the use of Visionaire Lighting and can be reproduced exclusively for those related to the company and under expressed written approval."), 0, 1, 'L');

	/***************************************************************************/

$pdf->Output("ncpr/$id_Folio.pdf", "F");
$pdf->Output("ncpr/$id_Folio.pdf", "I");
?>