<?php
	define('FPDF_FONTPATH', '../fpdf/font/');

	include("../SimpleImage/SimpleImage.class.php");
	require_once('../fpdf/fpdf.php');
	include_once("../DBManager.php");
	
	$objCon=new DBManager;

	class PDF extends FPDF
	{
		var $widths;
		var $aligns;

		function Header()
		{
			$this->SetFont('helvetica', '', 10);
			$this->Ln(30);
		}

		function Footer()
		{
			$this->SetY(-20);
			$this->SetFont('helvetica', 'B', 8);
		}
	}

	if ($objCon->conectar()==true)
	{
		date_default_timezone_set('America/Los_Angeles');

		/*****************************************************************/
		/* Revisa en la base de datos la cantidad de registros de NCPR's */

		$sql0="SELECT COUNT(*) FROM tbncprs";
		$result0=mysql_query($sql0) or die;

		/* Al número obtenido, se le suma 1 y se le asigna al NCPR */
		$id_Folio=(mysql_result($result0, 0)+1);

		/*****************************************************************/
		if(isset($_POST['NMG01']))
		{
			$GENERA='ALDO MATA';
		}
		if(isset($_POST['NMG02']))
		{
			$GENERA='CLAUDIA RENTERIA';
		}
		if(isset($_POST['NMG03']))
		{
			$GENERA='CRISTINA SOLIS';
		}
		if(isset($_POST['NMG04']))
		{
			$GENERA='DANIEL AGUIRRE';
		}
		if(isset($_POST['NMG05']))
		{
			$GENERA='GABRIELA HERNANDEZ';
		}
		if(isset($_POST['NMG06']))
		{
			$GENERA='HUGO AMEZQUITA';
		}
		if(isset($_POST['NMG07']))
		{
			$GENERA='HECTOR DIAZ';
		}
		if(isset($_POST['NMG08']))
		{
			$GENERA='JAAZIEL SERRANO';
		}
		if(isset($_POST['NMG09']))
		{
			$GENERA='OMAR GARCIA';
		}
		if(isset($_POST['NMG10']))
		{
			$GENERA='OSCAR VILLAREAL';
		}
		if(isset($_POST['NMG11']))
		{
			$GENERA='RAMON AVALOS';
		}
		if(isset($_POST['NMG12']))
		{
			$GENERA='CARLOS CALDERON';
		}
		if(isset($_POST['NMG13']))
		{
			$GENERA=$_POST['NMG14'];
		}		
				
		if(isset($_POST['NMR01']))
		{
			$REPORTA='ALBERTO ROMO';
		}
		if(isset($_POST['NMR02']))
		{
			$REPORTA='RENE CARDENAS';
		}
		if(isset($_POST['NMR03']))
		{
			$REPORTA='ANGELICA HERNANDEZ';
		}
		if(isset($_POST['NMR04']))
		{
			$REPORTA='MATEO SANDOVAL';
		}
		if(isset($_POST['NMR05']))
		{
			$REPORTA='OLIMPIA DOMINGUEZ';
		}
		if(isset($_POST['NMR06']))
		{
			$REPORTA='SANDRO ORDAZ';
		}
		if(isset($_POST['NMR07']))
		{
			$REPORTA='BALVANEDO GARCIA';
		}
		if(isset($_POST['NMR08']))
		{
			$REPORTA='IZACK GOLDBAUM';
		}
		if(isset($_POST['NMR09']))
		{
			$REPORTA='KARLOS JIMENEZ';
		}
		if(isset($_POST['NMR10']))
		{
			$REPORTA='MAURILIO AVALOS';
		}
		if(isset($_POST['NMR11']))
		{
			$REPORTA='RUBEN VALDEZ';
		}
		if(isset($_POST['NMR12']))
		{
			$REPORTA='JESUS GALVEZ';
		}
		if(isset($_POST['NMR13']))
		{
			$REPORTA=$_POST['NMR14'];
		}		

		if(isset($_POST['PRV01']))
		{
			$PROVEEDOR='ACCUTITE';
		}
		if(isset($_POST['PRV02']))
		{
			$PROVEEDOR='ACME';
		}
		if(isset($_POST['PRV03']))
		{
			$PROVEEDOR='ADAMS CAMPBELL';
		}
		if(isset($_POST['PRV04']))
		{
			$PROVEEDOR='ADVANCE';
		}
		if(isset($_POST['PRV05']))
		{
			$PROVEEDOR='ALANOD';
		}
		if(isset($_POST['PRV06']))
		{
			$PROVEEDOR='ALBRIGHT LIGHTING PLASTICS';
		}
		if(isset($_POST['PRV07']))
		{
			$PROVEEDOR='ALLEN PKG';
		}
		if(isset($_POST['PRV08']))
		{
			$PROVEEDOR='ALP LIGHTING COMPONENTS';
		}
		if(isset($_POST['PRV09']))
		{
			$PROVEEDOR='ALPHA CAST';
		}
		if(isset($_POST['PRV10']))
		{
			$PROVEEDOR='AMERICAN DE ROSA';
		}
		if(isset($_POST['PRV11']))
		{
			$PROVEEDOR='AMERICAN DIE CASTING, INC';
		}
		if(isset($_POST['PRV12']))
		{
			$PROVEEDOR='BENDER & WERTH';
		}
		if(isset($_POST['PRV13']))
		{
			$PROVEEDOR='BILL BROWN SALES';
		}
		if(isset($_POST['PRV14']))
		{
			$PROVEEDOR='BODINE';
		}
		if(isset($_POST['PRV15']))
		{
			$PROVEEDOR='BORRMAN';
		}
		if(isset($_POST['PRV16']))
		{
			$PROVEEDOR='CAST AND ENG PRODUCTS';
		}
		if(isset($_POST['PRV17']))
		{
			$PROVEEDOR='CIRCLE BOLT';
		}
		if(isset($_POST['PRV18']))
		{
			$PROVEEDOR='CIRCLE METAL SALES';
		}
		if(isset($_POST['PRV19']))
		{
			$PROVEEDOR='COAST';
		}
		if(isset($_POST['PRV20']))
		{
			$PROVEEDOR='CREST';
		}
		if(isset($_POST['PRV21']))
		{
			$PROVEEDOR='DELTECH';
		}
		if(isset($_POST['PRV22']))
		{
			$PROVEEDOR='ELECTROMARK';
		}
		if(isset($_POST['PRV23']))
		{
			$PROVEEDOR='EUGINO';
		}
		if(isset($_POST['PRV24']))
		{
			$PROVEEDOR='EXERGY';
		}
		if(isset($_POST['PRV25']))
		{
			$PROVEEDOR='FORMED';
		}
		if(isset($_POST['PRV26']))
		{
			$PROVEEDOR='FOLHAM';
		}
		if(isset($_POST['PRV27']))
		{
			$PROVEEDOR='FUSES UNLIMITED';
		}
		if(isset($_POST['PRV28']))
		{
			$PROVEEDOR='FUTURE';
		}
		if(isset($_POST['PRV29']))
		{
			$PROVEEDOR='G.E.';
		}
		if(isset($_POST['PRV30']))
		{
			$PROVEEDOR='GILLINDER';
		}
		if(isset($_POST['PRV31']))
		{
			$PROVEEDOR='GINO SHEET METAL';
		}
		if(isset($_POST['PRV32']))
		{
			$PROVEEDOR='GOOD IDEAS';
		}
		if(isset($_POST['PRV33']))
		{
			$PROVEEDOR='GRANDLITE';
		}
		if(isset($_POST['PRV34']))
		{
			$PROVEEDOR='H&M FOUNDRY';
		}
		if(isset($_POST['PRV35']))
		{
			$PROVEEDOR='HOPKINS';
		}
		if(isset($_POST['PRV36']))
		{
			$PROVEEDOR='IFSCO';
		}
		if(isset($_POST['PRV37']))
		{
			$PROVEEDOR='INDUSTRIAL GLASS';
		}
		if(isset($_POST['PRV38']))
		{
			$PROVEEDOR='INNOVATION';
		}
		if(isset($_POST['PRV39']))
		{
			$PROVEEDOR='INVENTRONICS';
		}
		if(isset($_POST['PRV40']))
		{
			$PROVEEDOR='J.V.S MACHINE SHOP';
		}
		if(isset($_POST['PRV41']))
		{
			$PROVEEDOR='KEN-MAC METALS';
		}
		if(isset($_POST['PRV42']))
		{
			$PROVEEDOR='KLENITUS';
		}
		if(isset($_POST['PRV43']))
		{
			$PROVEEDOR='KOPP';
		}
		if(isset($_POST['PRV44']))
		{
			$PROVEEDOR='LENDAR DESIGN INC.';
		}
		if(isset($_POST['PRV45']))
		{
			$PROVEEDOR='LEVITON';
		}
		if(isset($_POST['PRV46']))
		{
			$PROVEEDOR='LEXALITE';
		}
		if(isset($_POST['PRV47']))
		{
			$PROVEEDOR='MC MASTER';
		}
		if(isset($_POST['PRV48']))
		{
			$PROVEEDOR='METAL POLE';
		}
		if(isset($_POST['PRV49']))
		{
			$PROVEEDOR='MEYER';
		}
		if(isset($_POST['PRV50']))
		{
			$PROVEEDOR='NICHIA';
		}
		if(isset($_POST['PRV51']))
		{
			$PROVEEDOR='OMEGA LEADS';
		}
		if(isset($_POST['PRV52']))
		{
			$PROVEEDOR='ONLINE ELECTRONICS';
		}
		if(isset($_POST['PRV53']))
		{
			$PROVEEDOR='PACIFIC DIE';
		}
		if(isset($_POST['PRV54']))
		{
			$PROVEEDOR='PAX';
		}
		if(isset($_POST['PRV55']))
		{
			$PROVEEDOR='PENDANT SYSTEM';
		}
		if(isset($_POST['PRV56']))
		{
			$PROVEEDOR='PHILLIPS';
		}
		if(isset($_POST['PRV57']))
		{
			$PROVEEDOR='PLASTIC DEPOT';
		}
		if(isset($_POST['PRV58']))
		{
			$PROVEEDOR='POLYMER';
		}
		if(isset($_POST['PRV59']))
		{
			$PROVEEDOR='PRECISION';
		}
		if(isset($_POST['PRV60']))
		{
			$PROVEEDOR='QL COMPANY';
		}
		if(isset($_POST['PRV61']))
		{
			$PROVEEDOR='QSSI';
		}
		if(isset($_POST['PRV62']))
		{
			$PROVEEDOR='RIDOUT PLASTICS';
		}
		if(isset($_POST['PRV63']))
		{
			$PROVEEDOR='SABIC';
		}
		if(isset($_POST['PRV64']))
		{
			$PROVEEDOR='SAEHAN ELECTRONICS';
		}
		if(isset($_POST['PRV65']))
		{
			$PROVEEDOR='SAPA';
		}
		if(isset($_POST['PRV66']))
		{
			$PROVEEDOR='SERTEC';
		}
		if(isset($_POST['PRV67']))
		{
			$PROVEEDOR='SINCALIR GLASS';
		}
		if(isset($_POST['PRV68']))
		{
			$PROVEEDOR='SING WELDING';
		}
		if(isset($_POST['PRV69']))
		{
			$PROVEEDOR='STANDARD LIGHTING';
		}
		if(isset($_POST['PRV70']))
		{
			$PROVEEDOR='SYLVANIA';
		}
		if(isset($_POST['PRV71']))
		{
			$PROVEEDOR='TEMPWERKS';
		}
		if(isset($_POST['PRV72']))
		{
			$PROVEEDOR='TEXMEX';
		}
		if(isset($_POST['PRV73']))
		{
			$PROVEEDOR='THOMAS RESEARCH PRODUCTS';
		}
		if(isset($_POST['PRV74']))
		{
			$PROVEEDOR='TOTTEN';
		}
		if(isset($_POST['PRV75']))
		{
			$PROVEEDOR='TRANS-PACIFIC';
		}
		if(isset($_POST['PRV76']))
		{
			$PROVEEDOR='TUBE SER';
		}
		if(isset($_POST['PRV77']))
		{
			$PROVEEDOR='TUBULAR';
		}
		if(isset($_POST['PRV78']))
		{
			$PROVEEDOR='UNIVERSAL';
		}
		if(isset($_POST['PRV79']))
		{
			$PROVEEDOR='VENTURE';
		}
		if(isset($_POST['PRV80']))
		{
			$PROVEEDOR='VIRTICUS';
		}
		if(isset($_POST['PRV81']))
		{
			$PROVEEDOR='WAGO';
		}
		if(isset($_POST['PRV82']))
		{
			$PROVEEDOR='WEST MARINE';
		}
		if(isset($_POST['PRV83']))
		{
			$PROVEEDOR='N/A';
		}
		if(isset($_POST['PRV84']))
		{
			$PROVEEDOR=$_POST['PRV85'];
		}

		if(isset($_POST['AC001']))
		{
			$RECHAZO='AC001';
			$RECHAZODESCRIPCION='COMPONENTE INCORRECTO';
			$LOCALIZADEFECTO='ACCESS';
			$LOCALIZADEFECTODESC=' ACCESORIES / ACCESORIOS';
		}
		if(isset($_POST['AC002']))
		{
			$RECHAZO='AC002';
			$RECHAZODESCRIPCION='PRODUCTO DAÑADO';
			$LOCALIZADEFECTO='ACCESS';
			$LOCALIZADEFECTODESC='ACCESORIES / ACCESORIOS';
		}
		if(isset($_POST['AC003']))
		{
			$RECHAZO='AC003';
			$RECHAZODESCRIPCION='PRODUCTO INCOMPLETO';
			$LOCALIZADEFECTO='ACCESS';
			$LOCALIZADEFECTODESC='ACCESORIES / ACCESORIOS';
		}
		if(isset($_POST['AC004']))
		{
			$RECHAZO='AC004';
			$RECHAZODESCRIPCION='DISCREPANCIA EN CANTIDAD';
			$LOCALIZADEFECTO='ACCESS';
			$LOCALIZADEFECTODESC='ACCESORIES / ACCESORIOS';
		}
		if(isset($_POST['AC005']))
		{
			$RECHAZO='AC005';
			$RECHAZODESCRIPCION='ERROR EN MARCAJE';
			$LOCALIZADEFECTO='ACCESS';
			$LOCALIZADEFECTODESC='ACCESORIES / ACCESORIOS';
		}
		if(isset($_POST['AC006']))
		{
			$RECHAZO='AC006';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='ACCESS';
			$LOCALIZADEFECTODESC='ACCESORIES / ACCESORIOS';
		}
		if(isset($_POST['AD001']))
		{
			$RECHAZO='AD001';
			$RECHAZODESCRIPCION='PERFORACION FUERA DE ESPECIFICACION';
			$LOCALIZADEFECTO='ALMDR';
			$LOCALIZADEFECTODESC='AL FAB DRILLING / FAB AL PERFORADO';
		}
		if(isset($_POST['AD002']))
		{
			$RECHAZO='AD002';
			$RECHAZODESCRIPCION='PERFORACION O PROVISION EXTRA';
			$LOCALIZADEFECTO='ALMDR';
			$LOCALIZADEFECTODESC=' AL FAB DRILLING / FAB AL PERFORADO';
		}
		if(isset($_POST['AD003']))
		{
			$RECHAZO='AD003';
			$RECHAZODESCRIPCION='PERFORACION O PROVISION FALTANTE';
			$LOCALIZADEFECTO='ALMDR';
			$LOCALIZADEFECTODESC='AL FAB DRILLING / FAB AL PERFORADO';
		}
		if(isset($_POST['AD004']))
		{
			$RECHAZO='AD004';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='ALMDR';
			$LOCALIZADEFECTODESC='AL FAB DRILLING / FAB AL PERFORADO';
		}
		if(isset($_POST['AG001']))
		{
			$RECHAZO='AG001';
			$RECHAZODESCRIPCION='PULIDO EXCESIVO';
			$LOCALIZADEFECTO='ALMGR';
			$LOCALIZADEFECTODESC='AL FAB GRINDING / FAB AL PULIDO';
		}
		if(isset($_POST['AG002']))
		{
			$RECHAZO='AG002';
			$RECHAZODESCRIPCION='FALTANTE DE PULIDO';
			$LOCALIZADEFECTO='ALMGR';
			$LOCALIZADEFECTODESC='AL FAB GRINDING / FAB AL PULIDO';
		}
		if(isset($_POST['AG003']))
		{
			$RECHAZO='AG003';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='ALMGR';
			$LOCALIZADEFECTODESC='AL FAB GRINDING / FAB AL PULIDO';
		}
		if(isset($_POST['AW001']))
		{
			$RECHAZO='AW001';
			$RECHAZODESCRIPCION='APLICACION EXCESIVA DE SOLDADURA';
			$LOCALIZADEFECTO='ALMWL';
			$LOCALIZADEFECTODESC='AL FAB WELDING / FAB AL SOLDADURA';
		}
		if(isset($_POST['AW002']))
		{
			$RECHAZO='AW002';
			$RECHAZODESCRIPCION='FALTANTE DE SOLDADURA';
			$LOCALIZADEFECTO='ALMWL';
			$LOCALIZADEFECTODESC='AL FAB WELDING / FAB AL SOLDADURA';
		}
		if(isset($_POST['AW003']))
		{
			$RECHAZO='AW003';
			$RECHAZODESCRIPCION='APLICACION DISPAREJA DE SOLDADURA';
			$LOCALIZADEFECTO='ALMWL';
			$LOCALIZADEFECTODESC='AL FAB WELDING / FAB AL SOLDADURA';
		}
		if(isset($_POST['AW004']))
		{
			$RECHAZO='AW004';
			$RECHAZODESCRIPCION='PARTE MAL UBICADA';
			$LOCALIZADEFECTO='ALMWL';
			$LOCALIZADEFECTODESC='AL FAB WELDING / FAB AL SOLDADURA';
		}
		if(isset($_POST['AW005']))
		{
			$RECHAZO='AW005';
			$RECHAZODESCRIPCION='MATERIAL EQUIVOCADO EN PARTE';
			$LOCALIZADEFECTO='ALMWL';
			$LOCALIZADEFECTODESC='AL FAB WELDING / FAB AL SOLDADURA';
		}
		if(isset($_POST['AW006']))
		{
			$RECHAZO='AW006';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='ALMWL';
			$LOCALIZADEFECTODESC='AL FAB WELDING / FAB AL SOLDADURA';
		}
		if(isset($_POST['CN001']))
		{
			$RECHAZO='CN001';
			$RECHAZODESCRIPCION='ERROR EN PONCHADO';
			$LOCALIZADEFECTO='CNC01';
			$LOCALIZADEFECTODESC='CNC';
		}
		if(isset($_POST['CN002']))
		{
			$RECHAZO='CN002';
			$RECHAZODESCRIPCION='ERROR EN DOBLADO';
			$LOCALIZADEFECTO='CNC01';
			$LOCALIZADEFECTODESC='CNC';
		}
		if(isset($_POST['CN003']))
		{
			$RECHAZO='CN003';
			$RECHAZODESCRIPCION='DIMENSION FUERA DE ESPECIFICACION';
			$LOCALIZADEFECTO='CNC01';
			$LOCALIZADEFECTODESC='CNC';
		}
		if(isset($_POST['CN004']))
		{
			$RECHAZO='CN004';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='CNC01';
			$LOCALIZADEFECTODESC='CNC';
		}
		if(isset($_POST['DC001']))
		{
			$RECHAZO='DC001';
			$RECHAZODESCRIPCION='POROSIDAD';
			$LOCALIZADEFECTO='DCAST';
			$LOCALIZADEFECTODESC='DIE CASTING';
		}
		if(isset($_POST['DC002']))
		{
			$RECHAZO='DC002';
			$RECHAZODESCRIPCION='DEFORMACION';
			$LOCALIZADEFECTO='DCAST';
			$LOCALIZADEFECTODESC='DIE CASTING';
		}
		if(isset($_POST['DC003']))
		{
			$RECHAZO='DC003';
			$RECHAZODESCRIPCION='DEFLEXION';
			$LOCALIZADEFECTO='DCAST';
			$LOCALIZADEFECTODESC='DIE CASTING';
		}
		if(isset($_POST['DC004']))
		{
			$RECHAZO='DC004';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='DCAST';
			$LOCALIZADEFECTODESC='DIE CASTING';
		}
		if(isset($_POST['FA001']))
		{
			$RECHAZO='FA001';
			$RECHAZODESCRIPCION='ERROR EN ENSAMBLAJE';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA002']))
		{
			$RECHAZO='FA002';
			$RECHAZODESCRIPCION='PRODUCTO DAÑADO';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA003']))
		{
			$RECHAZO='FA003';
			$RECHAZODESCRIPCION='FALLA EN PRUEBA FUNCIONAL';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA004']))
		{
			$RECHAZO='FA004';
			$RECHAZODESCRIPCION='FALLA EN PRUEBA DIELECTRICA';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA005']))
		{
			$RECHAZO='FA005';
			$RECHAZODESCRIPCION='COMPONENTE INCORRECTO';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA006']))
		{
			$RECHAZO='FA006';
			$RECHAZODESCRIPCION='ERROR EN MARCAJE';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA007']))
		{
			$RECHAZO='FA007';
			$RECHAZODESCRIPCION='RESIDUOS DE MATERIAL';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA008']))
		{
			$RECHAZO='FA008';
			$RECHAZODESCRIPCION='COMPONENTE FALTANTE';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA009']))
		{
			$RECHAZO='FA009';
			$RECHAZODESCRIPCION='DAÑO EN CABLES';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA010']))
		{
			$RECHAZO='FA010';
			$RECHAZODESCRIPCION='COMPONENTE DAÑADO';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA011']))
		{
			$RECHAZO='FA011';
			$RECHAZODESCRIPCION='ERROR EN CABLEADO INTERIOR';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA012']))
		{
			$RECHAZO='FA012';
			$RECHAZODESCRIPCION='DAÑO EN CABLES DE CONEXION';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA013']))
		{
			$RECHAZO='FA013';
			$RECHAZODESCRIPCION='ERROR EN LONGITUD DE CABLES';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA014']))
		{
			$RECHAZO='FA014';
			$RECHAZODESCRIPCION='DAÑO POR MANEJO';
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FA015']))
		{
			$RECHAZO='FA015';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='FASSY';
			$LOCALIZADEFECTODESC='FINAL ASSEMBLY / ENSAMBLE FINAL';
		}
		if(isset($_POST['FO001']))
		{
			$RECHAZO='FO001';
			$RECHAZODESCRIPCION='POROSIDAD';
			$LOCALIZADEFECTO='FNDRY';
			$LOCALIZADEFECTODESC='FOUNDRY / FUNDICION';
		}
		if(isset($_POST['FO002']))
		{
			$RECHAZO='FO002';
			$RECHAZODESCRIPCION='DEFORMACION';
			$LOCALIZADEFECTO='FNDRY';
			$LOCALIZADEFECTODESC='FOUNDRY / FUNDICION';
		}
		if(isset($_POST['FO003']))
		{
			$RECHAZO='FO003';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='FNDRY';
			$LOCALIZADEFECTODESC='FOUNDRY / FUNDICION';
		}
		if(isset($_POST['LD001']))
		{
			$RECHAZO='LD001';
			$RECHAZODESCRIPCION='FALLA EN PRUEBA FUNCIONAL';
			$LOCALIZADEFECTO='LEDAS';
			$LOCALIZADEFECTODESC='LED ASSEMBLY / ENSAMBLE LED';
		}
		if(isset($_POST['LD002']))
		{
			$RECHAZO='LD002';
			$RECHAZODESCRIPCION='COMPONENTE INCORRECTO';
			$LOCALIZADEFECTO='LEDAS';
			$LOCALIZADEFECTODESC='LED ASSEMBLY / ENSAMBLE LED';
		}
		if(isset($_POST['LD003']))
		{
			$RECHAZO='LD003';
			$RECHAZODESCRIPCION='COMPONENTE FALTANTE';
			$LOCALIZADEFECTO='LEDAS';
			$LOCALIZADEFECTODESC='LED ASSEMBLY / ENSAMBLE LED';
		}
		if(isset($_POST['LD004']))
		{
			$RECHAZO='LD004';
			$RECHAZODESCRIPCION='DAÑO EN CABLES';
			$LOCALIZADEFECTO='LEDAS';
			$LOCALIZADEFECTODESC='LED ASSEMBLY / ENSAMBLE LED';
		}
		if(isset($_POST['LD005']))
		{
			$RECHAZO='LD005';
			$RECHAZODESCRIPCION='PRODUCTO DAÑADO';
			$LOCALIZADEFECTO='LEDAS';
			$LOCALIZADEFECTODESC='LED ASSEMBLY / ENSAMBLE LED';
		}
		if(isset($_POST['LD006']))
		{
			$RECHAZO='LD006';
			$RECHAZODESCRIPCION='COMPONENTE DAÑADO';
			$LOCALIZADEFECTO='LEDAS';
			$LOCALIZADEFECTODESC='LED ASSEMBLY / ENSAMBLE LED';
		}
		if(isset($_POST['LD007']))
		{
			$RECHAZO='LD007';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='LEDAS';
			$LOCALIZADEFECTODESC='LED ASSEMBLY / ENSAMBLE LED';
		}
		if(isset($_POST['OP001']))
		{
			$RECHAZO='OP001';
			$RECHAZODESCRIPCION='WRONG MATERIAL USED IN ASSEMBLY / MATERIAL EQUIVOCADO EN ENSAMBLAJE';
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['OP002']))
		{
			$RECHAZO='OP002';
			$RECHAZODESCRIPCION='SCRATCHES / RAYONES';
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['OP003']))
		{
			$RECHAZO='OP003';
			$RECHAZODESCRIPCION='MISSING RIVET / FALTANTE DE REMACHE';
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['OP004']))
		{
			$RECHAZO='OP004';
			$RECHAZODESCRIPCION='MOSSING HOLE - PROVISION / FALTANTE DE HOYO - PROVISION';
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['OP005']))
		{
			$RECHAZO='OP005';
			$RECHAZODESCRIPCION='WRONG LAMP SOCKET / BASE PARA FOCO EQUIVOCADA';
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['OP006']))
		{
			$RECHAZO='OP006';
			$RECHAZODESCRIPCION='MISSING LAMP SOCKET / BASE PARA FOCO FALTANTE';
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['OP007']))
		{
			$RECHAZO='OP007';
			$RECHAZODESCRIPCION='DEFORMATION / DEFORMACION';
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['OP008']))
		{
			$RECHAZO='OP008';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='OPASS';
			$LOCALIZADEFECTODESC='OPTICS ASSEMBLY / ENSAMBLE REFLECTORES';
		}
		if(isset($_POST['CR001']))
		{
			$RECHAZO='CR001';
			$RECHAZODESCRIPCION='DESPRENDIMIENTO DE PISTA';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR002']))
		{
			$RECHAZO='CR002';
			$RECHAZODESCRIPCION='DEFECTO EN SOLDADO';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR003']))
		{
			$RECHAZO='CR003';
			$RECHAZODESCRIPCION='FALTA DE EPOXICO';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR004']))
		{
			$RECHAZO='CR004';
			$RECHAZODESCRIPCION='EXCESO DE EPOXICO';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR005']))
		{
			$RECHAZO='CR005';
			$RECHAZODESCRIPCION='DAÑO EN CABLES';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR006']))
		{
			$RECHAZO='CR006';
			$RECHAZODESCRIPCION='DESALINEACION DE CLUSTER / LENS';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR007']))
		{
			$RECHAZO='CR007';
			$RECHAZODESCRIPCION='GASKET EQUIVOCADO';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR008']))
		{
			$RECHAZO='CR008';
			$RECHAZODESCRIPCION='FALTA DE CURADO UV';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR009']))
		{
			$RECHAZO='CR009';
			$RECHAZODESCRIPCION='CLUSTER / LENS EQUIVOCADO';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR010']))
		{
			$RECHAZO='CR010';
			$RECHAZODESCRIPCION='PCB EQUIVOCADO';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR011']))
		{
			$RECHAZO='CR011';
			$RECHAZODESCRIPCION='DAÑOS DURANTE ENSAMBLAJE';
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['CR012']))
		{
			$RECHAZO='CR012';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='PCBCR';
			$LOCALIZADEFECTODESC='PCB CLEAN ROOM / PCB CUARTO LIMPIO';
		}
		if(isset($_POST['PI001']))
		{
			$RECHAZO='PI001';
			$RECHAZODESCRIPCION='BURBUJAS DE AIRE';
			$LOCALIZADEFECTO='PINRD';
			$LOCALIZADEFECTODESC='PLASTIC INJECTION (RD) / INYECCION PLASTICO (RD)';
		}
		if(isset($_POST['PI002']))
		{
			$RECHAZO='PI002';
			$RECHAZODESCRIPCION='MANCHAS';
			$LOCALIZADEFECTO='PINRD';
			$LOCALIZADEFECTODESC='PLASTIC INJECTION (RD) / INYECCION PLASTICO (RD)';
		}
		if(isset($_POST['PI003']))
		{
			$RECHAZO='PI003';
			$RECHAZODESCRIPCION='DECOLORACION';
			$LOCALIZADEFECTO='PINRD';
			$LOCALIZADEFECTODESC='PLASTIC INJECTION (RD) / INYECCION PLASTICO (RD)';
		}
		if(isset($_POST['PI004']))
		{
			$RECHAZO='PI004';
			$RECHAZODESCRIPCION='QUEBRADURAS';
			$LOCALIZADEFECTO='PINRD';
			$LOCALIZADEFECTODESC='PLASTIC INJECTION (RD) / INYECCION PLASTICO (RD)';
		}
		if(isset($_POST['PI005']))
		{
			$RECHAZO='PI005';
			$RECHAZODESCRIPCION='DEFORMACION';
			$LOCALIZADEFECTO='PINRD';
			$LOCALIZADEFECTODESC='PLASTIC INJECTION (RD) / INYECCION PLASTICO (RD)';
		}
		if(isset($_POST['PI006']))
		{
			$RECHAZO='PI006';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='PINRD';
			$LOCALIZADEFECTODESC='PLASTIC INJECTION (RD) / INYECCION PLASTICO (RD)';
		}
		if(isset($_POST['PC001']))
		{
			$RECHAZO='PC001';
			$RECHAZODESCRIPCION='AMPOLLAS';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC002']))
		{
			$RECHAZO='PC002';
			$RECHAZODESCRIPCION='COLOR INCONSISTENTE';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC003']))
		{
			$RECHAZO='PC003';
			$RECHAZODESCRIPCION='CONTAMINACION';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC004']))
		{
			$RECHAZO='PC004';
			$RECHAZODESCRIPCION='PRODUCTO DAÑADO';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC005']))
		{
			$RECHAZO='PC005';
			$RECHAZODESCRIPCION='DECOLORACION';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC006']))
		{
			$RECHAZO='PC006';
			$RECHAZODESCRIPCION='RESIDUO DE PASTA';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC007']))
		{
			$RECHAZO='PC007';
			$RECHAZODESCRIPCION='RESIDUO DE GRASA';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC008']))
		{
			$RECHAZO='PC008';
			$RECHAZODESCRIPCION='CASCARA DE NARANJA';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC009']))
		{
			$RECHAZO='PC009';
			$RECHAZODESCRIPCION='EXCESO DE PINTURA';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC010']))
		{
			$RECHAZO='PC010';
			$RECHAZODESCRIPCION='POROSIDAD';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC011']))
		{
			$RECHAZO='PC011';
			$RECHAZODESCRIPCION='MALA ADHERENCIA';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC012']))
		{
			$RECHAZO='PC012';
			$RECHAZODESCRIPCION='FALTA DE COBERTURA';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC013']))
		{
			$RECHAZO='PC013';
			$RECHAZODESCRIPCION='RAYONES';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC014']))
		{
			$RECHAZO='PC014';
			$RECHAZODESCRIPCION='COLOR EQUIVOCADO';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC015']))
		{
			$RECHAZO='PC015';
			$RECHAZODESCRIPCION='RESIDUO DE GRNALLA';
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['PC016']))
		{
			$RECHAZO='PC016';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='PCOAT';
			$LOCALIZADEFECTODESC='POWDER COAT / PINTURA';
		}
		if(isset($_POST['SM001']))
		{
			$RECHAZO='SM001';
			$RECHAZODESCRIPCION='PCB MAL IDENTIFICADO';
			$LOCALIZADEFECTO='SMTRD';
			$LOCALIZADEFECTODESC='SMT ROOM (RD) / CUARTO SMT (RD)';
		}
		if(isset($_POST['SM002']))
		{
			$RECHAZO='SM002';
			$RECHAZODESCRIPCION='DESPRENDIMIENTO DE DIODO (LED)';
			$LOCALIZADEFECTO='SMTRD';
			$LOCALIZADEFECTODESC='SMT ROOM (RD) / CUARTO SMT (RD)';
		}
		if(isset($_POST['SM003']))
		{
			$RECHAZO='SM003';
			$RECHAZODESCRIPCION='RAYONES';
			$LOCALIZADEFECTO='SMTRD';
			$LOCALIZADEFECTODESC='SMT ROOM (RD) / CUARTO SMT (RD)';
		}
		if(isset($_POST['SM004']))
		{
			$RECHAZO='SM004';
			$RECHAZODESCRIPCION='MANCHAS';
			$LOCALIZADEFECTO='SMTRD';
			$LOCALIZADEFECTODESC='SMT ROOM (RD) / CUARTO SMT (RD)';
		}
		if(isset($_POST['SM005']))
		{
			$RECHAZO='SM005';
			$RECHAZODESCRIPCION='QUEBRADURAS';
			$LOCALIZADEFECTO='SMTRD';
			$LOCALIZADEFECTODESC='SMT ROOM (RD) / CUARTO SMT (RD)';
		}
		if(isset($_POST['SM006']))
		{
			$RECHAZO='SM006';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='SMTRD';
			$LOCALIZADEFECTODESC='SMT ROOM (RD) / CUARTO SMT (RD)';
		}
		if(isset($_POST['SP001']))
		{
			$RECHAZO='SP001';
			$RECHAZODESCRIPCION='DIMENSION FUERA DE ESPECIFICACION';
			$LOCALIZADEFECTO='SPNNG';
			$LOCALIZADEFECTODESC='SPINNING';
		}
		if(isset($_POST['SP002']))
		{
			$RECHAZO='SP002';
			$RECHAZODESCRIPCION='MATERIAL EQUIVOCADO EN PARTE';
			$LOCALIZADEFECTO='SPNNG';
			$LOCALIZADEFECTODESC='SPINNING';
		}
		if(isset($_POST['SP003']))
		{
			$RECHAZO='SP003';
			$RECHAZODESCRIPCION='QUEBRADURAS';
			$LOCALIZADEFECTO='SPNNG';
			$LOCALIZADEFECTODESC='SPINNING';
		}
		if(isset($_POST['SP004']))
		{
			$RECHAZO='SP004';
			$RECHAZODESCRIPCION='DEFORMACION';
			$LOCALIZADEFECTO='SPNNG';
			$LOCALIZADEFECTODESC='SPINNING';
		}
		if(isset($_POST['SP005']))
		{
			$RECHAZO='SP005';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='SPNNG';
			$LOCALIZADEFECTODESC='SPINNING';
		}
		if(isset($_POST['ST001']))
		{
			$RECHAZO='ST001';
			$RECHAZODESCRIPCION='PERFORACION FUERA DE ESPECIFICACION';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST002']))
		{
			$RECHAZO='ST002';
			$RECHAZODESCRIPCION='PERFORACION O PROVISION EXTRA';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST003']))
		{
			$RECHAZO='ST003';
			$RECHAZODESCRIPCION='PERFORACION O PROVISION FALTANTE';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST004']))
		{
			$RECHAZO='ST004';
			$RECHAZODESCRIPCION='APLICACION EXCESIVA DE SOLDADURA';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST005']))
		{
			$RECHAZO='ST005';
			$RECHAZODESCRIPCION='FALTANTE DE SOLDADURA';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST006']))
		{
			$RECHAZO='ST006';
			$RECHAZODESCRIPCION='APLICACION DISPAREJA DE SOLDADURA';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST007']))
		{
			$RECHAZO='ST007';
			$RECHAZODESCRIPCION='PARTE MAL UBICADA';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST008']))
		{
			$RECHAZO='ST008';
			$RECHAZODESCRIPCION='MATERIAL EQUIVOCADO EN PARTE';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST009']))
		{
			$RECHAZO='ST009';
			$RECHAZODESCRIPCION='PULIDO EXCESIVO';
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['ST010']))
		{
			$RECHAZO='ST010';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='STLFB';
			$LOCALIZADEFECTODESC='STEEL FABRICATION / FABRICACION ACERO';
		}
		if(isset($_POST['SE001']))
		{
			$RECHAZO='SE001';
			$RECHAZODESCRIPCION='COMPONENTE INCORRECTO';
			$LOCALIZADEFECTO='SPEXT';
			$LOCALIZADEFECTODESC='SUPPLIER (EXTERNAL) / PROVEEDOR (EXTERNO)';
		}
		if(isset($_POST['SE002']))
		{
			$RECHAZO='SE002';
			$RECHAZODESCRIPCION='PRODUCTO DAÑADO';
			$LOCALIZADEFECTO='SPEXT';
			$LOCALIZADEFECTODESC='SUPPLIER (EXTERNAL) / PROVEEDOR (EXTERNO)';
		}
		if(isset($_POST['SE003']))
		{
			$RECHAZO='SE003';
			$RECHAZODESCRIPCION='PRODUCTO INCOMPLETO';
			$LOCALIZADEFECTO='SPEXT';
			$LOCALIZADEFECTODESC='SUPPLIER (EXTERNAL) / PROVEEDOR (EXTERNO)';
		}
		if(isset($_POST['SE004']))
		{
			$RECHAZO='SE004';
			$RECHAZODESCRIPCION='DISCREPANCIA EN CANTIDAD';
			$LOCALIZADEFECTO='SPEXT';
			$LOCALIZADEFECTODESC='SUPPLIER (EXTERNAL) / PROVEEDOR (EXTERNO)';
		}
		if(isset($_POST['SE005']))
		{
			$RECHAZO='SE005';
			$RECHAZODESCRIPCION='ERROR EN MARCAJE';
			$LOCALIZADEFECTO='SPEXT';
			$LOCALIZADEFECTODESC='SUPPLIER (EXTERNAL) / PROVEEDOR (EXTERNO)';
		}
		if(isset($_POST['SE006']))
		{
			$RECHAZO='SE006';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='SPEXT';
			$LOCALIZADEFECTODESC='SUPPLIER (EXTERNAL) / PROVEEDOR (EXTERNO)';
		}
		if(isset($_POST['WH001']))
		{
			$RECHAZO='WH001';
			$RECHAZODESCRIPCION='COMPONENTE ENTREGADO INCORRECTO';
			$LOCALIZADEFECTO='WHSRE';
			$LOCALIZADEFECTODESC='WAREHOUSE / ALMACEN';
		}
		if(isset($_POST['WH002']))
		{
			$RECHAZO='WH002';
			$RECHAZODESCRIPCION='DAÑO POR MANEJO';
			$LOCALIZADEFECTO='WHSRE';
			$LOCALIZADEFECTODESC='WAREHOUSE / ALMACEN';
		}
		if(isset($_POST['WH003']))
		{
			$RECHAZO='WH003';
			$RECHAZODESCRIPCION='PRODUCTO INCOMPLETO';
			$LOCALIZADEFECTO='WHSRE';
			$LOCALIZADEFECTODESC='WAREHOUSE / ALMACEN';
		}
		if(isset($_POST['WH004']))
		{
			$RECHAZO='WH004';
			$RECHAZODESCRIPCION='DISCREPANCIA EN CANTIDAD';
			$LOCALIZADEFECTO='WHSRE';
			$LOCALIZADEFECTODESC='WAREHOUSE / ALMACEN';
		}
		if(isset($_POST['WH005']))
		{
			$RECHAZO='WH005';
			$RECHAZODESCRIPCION='COMPONENTES MEZCLADOS';
			$LOCALIZADEFECTO='WHSRE';
			$LOCALIZADEFECTODESC='WAREHOUSE / ALMACEN';
		}
		if(isset($_POST['WH006']))
		{
			$RECHAZO='WH006';
			$RECHAZODESCRIPCION=$_POST['razonotro'];
			$LOCALIZADEFECTO='WHSRE';
			$LOCALIZADEFECTODESC='WAREHOUSE / ALMACEN';
		}
			
		if(isset($_POST['SPROC']))
		{
			$LOCACIONDEFECTO='SPROC';
			$LOCACIONDEFECTODESC='INSPECCION AL INICIO DEL PROCESO / START OF PROCESS INSPECTION';
		}	
		if(isset($_POST['IPROC']))
		{
			$LOCACIONDEFECTO='IPROC';
			$LOCACIONDEFECTODESC='DURANTE EL PROCESO / IN PROCESS INSPECTION';
		}	
		if(isset($_POST['EPROC']))
		{
			$LOCACIONDEFECTO='EPROC';
			$LOCACIONDEFECTODESC='INSPECCION AL FINAL DE PROCESO / END OF PROCESS INSPECTION';
		}	
		if(isset($_POST['WHSRE']))
		{
			$LOCACIONDEFECTO='WHSRE';
			$LOCACIONDEFECTODESC='ALMACEN (EN INVENTARIO) / WHAREHOUSE (IN STOCK)';
		}	
		if(isset($_POST['INCOM']))
		{
			$LOCACIONDEFECTO='INCOM';
			$LOCACIONDEFECTODESC='INSPECCION DE RECIBOS / INCOMING INSPECTION';
		}	
		if(isset($_POST['SHIPG']))
		{
			$LOCACIONDEFECTO='SHIPG';
			$LOCACIONDEFECTODESC='EMBARQUES / SHIPPING';
		}	
		if(isset($_POST['LOCACIONDEF']))
		{
			$LOCACIONDEFECTO='LOCOTHER';
			$LOCACIONDEFECTODESC=$_POST['LOCACIONDEF1'];
		}
	
		if(isset($_POST['SCRAP']))
		{
			$DISPOSICION='SCRAP';
			$DISPOSICIONDESCRIPCION='DESECHAR (SCRAP) / SCRAP';
		}	
		if(isset($_POST['RT2RD']))
		{
			$DISPOSICION='RT2RD';
			$DISPOSICIONDESCRIPCION='REGRESAR A RANCHO DOMINGUEZ / RETURN TO RANCHO DOMINGUEZ';
		}	
		if(isset($_POST['RT2VD']))
		{
			$DISPOSICION='RT2VD';
			$DISPOSICIONDESCRIPCION='REGRESAR A PROVEEDOR / RETURN TO SUPPLIER (EXTERNAL)';
		}	
		if(isset($_POST['USEAI']))
		{
			$DISPOSICION='USEAI';
			$DISPOSICIONDESCRIPCION='USAR COMO ESTA / USE AS IS';
		}	
		if(isset($_POST['REWRK']))
		{
			$DISPOSICION='REWRK';
			$DISPOSICIONDESCRIPCION='RE-TRABAJAR / REWORK';
		}	
		if(isset($_POST['SRTQA']))
		{
			$DISPOSICION='SRTQA';
			$DISPOSICIONDESCRIPCION='SEPARAR / SORT';
		}	
		if(isset($_POST['TBDQA']))
		{
			$DISPOSICION='TBDQA';
			$DISPOSICIONDESCRIPCION='POR DEFINIR (QA) / TO BE DETERMINED (QA)';
		}		
		if(isset($_POST['DISPOTRO']))
		{
			$DISPOSICION='DISPOTHER';
			$DISPOSICIONDESCRIPCION=$_POST['DISPOTRO1'];
		}
		
		if(isset($_POST['TURNO01']))
		{
			$TURNO='PRIMER TURNO / 1ST SHIFT';
		}	
		if(isset($_POST['TURNO02']) )
		{
			$TURNO='SEGUNDO TURNO / 2ND SHIFT';
		}
		
		$ORDEN=strtoupper($_POST['orden']);
		$PARTE=strtoupper($_POST['parte']);
		$FECHAENVIO=$_POST['fechaenvio'];
		$DESCRIPCIONPARTE=strtoupper($_POST['descripcionparte']);
		
		$FECHA=date("m-j-y");
		$HORA=date("H:i");
		
		$PIEZASORDEN=$_POST['piezasorden'];
		$PIEZASRECHAZADAS=$_POST['piezasrechazadas'];
		$DESCRIPCIONFALLA=strtoupper($_POST['descripcionfalla']);

		$sql="INSERT INTO tbncprs VALUES('NULL', '$ORDEN', '$PARTE', '$TURNO', '$FECHAENVIO', '$DESCRIPCIONPARTE', '$PROVEEDOR', '$REPORTA', '$GENERA', '$FECHA', '$HORA', '$LOCALIZADEFECTO', '$LOCALIZADEFECTODESC', '$PIEZASORDEN', '$PIEZASRECHAZADAS', '$RECHAZO', '$RECHAZODESCRIPCION', '$DESCRIPCIONFALLA', '$LOCACIONDEFECTO', '$LOCACIONDEFECTODESC', '$DISPOSICION', '$DISPOSICIONDESCRIPCION')";
		$result=mysql_query($sql);
		
		/*echo "<script language='JavaScript'>
			window.alert('El NCPR ha sido creado.') 
			window.location.href='../mail.php?id_folio=$id_Folio[id_Folio]'
			</script>";*/
	}	

	/****************** Variables para el PDF *******************/

	$DISPOSICIONPD=$DISPOSICION .' - '. $DISPOSICIONDESCRIPCION;
	$LOCALIZADD=$LOCALIZADEFECTO .' - '. $LOCALIZADEFECTODESC;
	$LOCACIONFD=$LOCACIONDEFECTO .' - '. $LOCACIONDEFECTODESC;
	$RECHAZOD=$RECHAZO .' - '. $RECHAZODESCRIPCION;

	/* Declaración de variables */
	$documento_no="VL-PA-SGC-001-F02";
	$pagina="1 OF 1";
	$document="NON-CONFORMING PRODUCT REPORT";
	$revision="4";
	$fecha=$FECHA;
	$nombre_documento="NON-CONFORMING PRODUCT REPORT (ENGLISH)";
			
	/* Fin de declaración de variables */

	/* Variables del sistema*/
	$setx=13;
	$cellx=45;
	$cellsize=194;
	$setderecha=99;
	/* Fin de variables del sistema*/

	// PDF(Vertical, Milimetros, Tamaño Carta)
	$pdf=new PDF('P', 'mm', 'Letter');
	$pdf->AddPage();
	$pdf->SetFont('helvetica', '', '8');
	
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(11, 13, 198, 235);   // Contenedor principal
	
	$pdf->Image('../img/Logo.jpg', 27, 17, 65); //Imagen de logotipo
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 15, 97, 15);    // Recuadro del Logo

	$pdf->SetXY(110, 19);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(63, 5, "DOCUMENTO NO.:", 0, 1, 'C', 'F');

	$pdf->SetXY(110, 24);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(63, 5, $documento_no, 0, 1, 'C');

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(110, 15, 63, 15);

	/***************************************************************************/
	
	$pdf->SetXY(173, 19);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->cell(34, 5, "PAGINA:", 0, 1, 'C');

	$pdf->SetXY(173, 24);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(34, 5, $pagina, 0, 1, 'C');

	$pdf->SetXY(115, 580);
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(173, 15, 34, 15);

	/***************************************************************************/

	$pdf->SetXY($setx, 31.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->cell(19, 5, "DOCUMENT:", 0, 1, 'L');

	$pdf->SetXY($setx+19, 31.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(60, 5, $document, 0, 1, 'L');

	$pdf->SetXY($setx, 35.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->Cell(16, 5, "REVISION:", 0, 1, 'L');

	$pdf->SetXY($setx+16, 35.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(63, 5, $revision, 0, 1, 'L');

	$pdf->SetXY($setx, 39.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->Cell(12, 5, "FECHA:", 0, 1, 'L');

	$pdf->SetXY($setx+12, 39.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(66, 5, $fecha, 0, 1, 'L');
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 30, 97, 15);    // DOCUMENT

	/***************************************************************************/

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->SetXY(110, 31.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->Cell(97, 5, "NOMBRE DEL DOCUMENTO:", 0, 1, 'C');

	$pdf->SetXY(110, 35.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(97, 5, $nombre_documento, 0, 1, 'C');

	$pdf->Rect(110, 30, $setderecha-2, 15);    // NOMBRE DEL DOCUMENTO

	/***************************************************************************/

	$pdf->SetXY(110, 50);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(171, 171, 171); // Color Gris
	// L (El texto de la celda lo envia a la derecha), F (Rellena la celda con el color seleccionado)
	$pdf->Cell(63, 5, "Folio No. (File No.):", 1, 1, 'L', 'C');

	$pdf->SetXY(173, 50);
	$pdf->SetFont('Arial', '', '8');
	$pdf->SetTextColor(51, 51, 153); // Color Morado
	$pdf->Cell(34, 5, $id_Folio, 1, 1, 'C');

	/***************************************************************************/

	$pdf->SetXY($setx, 55);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(171, 171, 171); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("(1) Información general del reporte (General Information of the report)"), 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 60);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Multicell($cellx+6, 10, "Reportado por (Reported by):", 1, 1, 'L', 'F');
	
	$pdf->SetXY(64, 60);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->Cell(46, 10, utf8_decode($REPORTA), 1, 1, 'C', 'F');
	 
	$pdf->SetXY(110, 60);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell(47, 10, "Generado por (Generated by):", 1, 1, 'C', 'F');

	$pdf->SetXY(155, 60);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->Cell(52, 10, utf8_decode($GENERA), 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 70);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell($cellx+6, 10, utf8_decode("Área/Department (Localized defect):"), 1, 1, 'L', 'F');
	
	$pdf->SetXY(64, 70);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(46, 10, utf8_decode(''), 1, 1, 'C', 'F');

	$pdf->SetXY(110, 70);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell(45, 10, utf8_decode("Área/Department (Origin defect):"), 1, 1, 'L', 'F');

	$pdf->SetXY(156, 72);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->Multicell(50, 3.5, utf8_decode($LOCALIZADD), 0, 1, 'C', 'F');

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(155, 70, 52, 10);    // $LOCALIZADD

	/***************************************************************************/
	
	$pdf->SetXY($setx, 80);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell($cellx+6, 5, "Fecha (Date):", 1, 1, 'L', 'F');

	$pdf->SetXY(64, 80);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(22, 5, $FECHA, 1, 1, 'C', 'F');

	$pdf->SetXY(86, 80);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell(24, 5, "Hora (Hour):", 1, 1, 'L', 'F');

	$pdf->SetXY(110, 80);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(22, 5, $HORA, 1, 1, 'C', 'F');

	$pdf->SetXY(132, 80);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell(23, 5, "Turno (Shift):", 1, 1, 'L', 'F');

	$pdf->SetXY(155, 80);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(52, 5, $TURNO, 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 85);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell(51, 5, "Orden No. (Order no.):", 1, 1, 'L', 'F');

	$pdf->SetXY(64, 85);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(46, 5, $ORDEN, 1, 1, 'C', 'F');

	$pdf->SetXY(110, 85);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell($cellx+2, 5, "Fecha de Envio (Shipping date):", 1, 1, 'L', 'F');

	$pdf->SetXY(155, 85);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(52, 5, $FECHAENVIO, 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 90);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell($cellx+6, 5, "No. De Parte (Part No.):", 1, 1, 'L', 'F');

	$pdf->SetXY(64, 90);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(143, 5, $PARTE, 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 95);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell($cellx+6, 5, utf8_decode("Descripción del producto o la parte (Product/Part description):"), 1, 1, 'L', 'F');

	$pdf->SetXY(64, 95);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(143, 10, utf8_decode($DESCRIPCIONPARTE), 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 105);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell($cellx+6, 10, "Nombre del proveedor (Vendor name):", 1, 1, 'L', 'F');

	$pdf->SetXY(64, 105);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(143, 10, utf8_decode($PROVEEDOR), 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 115);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell(73, 10, "No. de piezas en la orden (No. Of pieces in the order):", 1, 1, 'L', 'F');

	$pdf->SetXY(86, 115);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(24, 10, $PIEZASORDEN, 1, 1, 'C', 'F');

	$pdf->SetXY(110, 115);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell(65, 5, "No. De piezas rechazadas (No. of pieces rejected):", 1, 1, 'L', 'F');

	$pdf->SetXY(173, 115);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(34, 10, $PIEZASRECHAZADAS, 1, 1, 'C', 'F');

	/***************************************************************************/
	
	$pdf->SetXY($setx, 125);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(171, 171, 171); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("(2) Razón de rechazo (Reason for rejection)"), 1, 1, 'C', 'F');

	/***************************************************************************/
	
	$pdf->SetXY($setx, 130);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell($cellsize, 10, utf8_decode($RECHAZOD), 1, 1, 'C', 'F');	
	
	/***************************************************************************/
	
	$pdf->SetXY($setx, 140);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(171, 171, 171); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("(3) Descripción de la falla reportada (Description of reported failure)"), 1, 1, 'C', 'F');

	/***************************************************************************/
	
	$pdf->SetXY($setx, 146);
	$pdf->SetTextColor(31, 73, 125);   // Color Azul
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Multicell(190, 4, utf8_decode($DESCRIPCIONFALLA), 0, 1, 'C', 'F');	
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 145, $cellsize, 20); // (3) Descripción  
	
	/***************************************************************************/
	
	$pdf->SetXY($setx, 165);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(171, 171, 171); // Color Gris

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(110, 165.1, $setderecha-2, 10, 'F'); // (5) Disposición del producto

	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell(97, 10, utf8_decode("(4) Localización del defecto (Detected on)"), 1, 1, 'C', 'F');

	$pdf->SetXY(111, 166);
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(95, 4, utf8_decode("(5) Disposición del producto no conforme (Disposition of non conformant product)"), 0, 1, 'C');

	/***************************************************************************/

	$pdf->SetXY($setx+1, 176);
	$pdf->SetTextColor(31, 73, 125);    // Color Azul
	$pdf->SetFillColor(255, 255, 255);  // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(95, 4, utf8_decode($LOCACIONFD), 0, 1, 'C', 'F');

	$pdf->SetXY(111, 176);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(95, 4, utf8_decode($DISPOSICIONPD), 0, 1, 'C', 'F');

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 175, $setderecha-2, 10); // (4) Localización del defecto*/
	$pdf->Rect(110, 175, $setderecha-2, 10);   // (5) Disposición del producto  
	$pdf->Rect(110, 165, $setderecha-2, 10);   // $DISPOSICIONPD  

	/***************************************************************************/

	$pdf->SetXY($setx, 185);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(171, 171, 171); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("Archivo fotográfico (Photo archive)"), 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 190);
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(64.6, 56, utf8_decode(""), 1, 1, 'C');

	$pdf->SetXY($setx+64.6, 190);

	// C (Centra el texto de la celda)
	$pdf->Multicell(64.6, 56, utf8_decode(""), 1, 1, 'C');

	$pdf->SetXY($setx+129, 190);
	// C (Centra el texto de la celda)
	$pdf->Multicell(65, 56, utf8_decode(""), 1, 1, 'C');

    /***************************************************************************/

    $obj_simpleimage=new SimpleImage();       	  											       // Sea crea un objeto de la clase SimpleImage()

    $foto1=$_FILES['foto1']['name'];		  	   												   // Obtenemos el nombre de la foto1 	
	$foto2=$_FILES['foto2']['name'];          	  												   // Obtenemos el nombre de la foto2 	
	$foto3=$_FILES['foto3']['name'];		  	  												   // Obtenemos el nombre de la foto3 	

	$ruta_foto1=$_FILES['foto1']['tmp_name']; 	   												   // Guarda la foto1 en una carpeta temporalmente	
	$ruta_foto2=$_FILES['foto2']['tmp_name']; 	  												   // Guarda la foto1 en una carpeta temporalmente	
	$ruta_foto3=$_FILES['foto3']['tmp_name']; 	   												   // Guarda la foto1 en una carpeta temporalmente	  

	$destino_foto1="../fotos/".$foto1;		  	   												   // Generamos la dirección donde seguardará la foto1
	$destino_foto2="../fotos/".$foto2;		 	  												   // Generamos la dirección donde seguardará la foto1
	$destino_foto3="../fotos/".$foto3;		 	  											       // Generamos la dirección donde seguardará la foto1

	$foto1_nuevo=time().rand().".jpg";		       												   // Generamos un nuevo nombre aleatorio para la foto1
	$foto2_nuevo=time().rand().".jpg";		       												   // Generamos un nuevo nombre aleatorio para la foto2
	$foto3_nuevo=time().rand().".jpg";		  	  												   // Generamos un nuevo nombre aleatorio para la foto3

	$destino_foto1_nuevo="../fotos/".$foto1_nuevo; 												   // Generamos la dirección donde seguardará la foto1_nuevo
	$destino_foto2_nuevo="../fotos/".$foto2_nuevo; 												   // Generamos la dirección donde seguardará la foto2_nuevo
	$destino_foto3_nuevo="../fotos/".$foto3_nuevo; 												   // Generamos la dirección donde seguardará la foto3_nuevo

	if($foto1 && $foto2 && $foto3!=NULL) // Si las variables $foto1, $foto2 y $foto3 contienen imagenes, las tres imágenes se agregarán al archivo pdf
	{
		copy($ruta_foto1, $destino_foto1); 														   // Guarda la foto1 en el servidor
		copy($ruta_foto2, $destino_foto2); 														   // Guarda la foto1 en el servidor
		copy($ruta_foto3, $destino_foto3); 														   // Guarda la foto1 en el servidor

		$obj_simpleimage->load($destino_foto1);													   // Carga la foto1
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4); // Redimensiona la imágen a 1/4 de su tamaño real
		$obj_simpleimage->save($destino_foto1_nuevo);											   // Guarda los cambios realizados							

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto1 es maá grande que el alto ... 
		{																						   
			$pdf->Image($destino_foto1_nuevo, 15.3,  200, 60); 									   // ... Agrega la foto1 en el archivo pdf en forma horizontal
		}					
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto1_nuevo, 30,  191.3, 30);                                     // ... Agrega la foto1 en el archivo pdf en forma vertical
		}

		$obj_simpleimage->load($destino_foto2);													   // Carga la imágen foto2
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4); // Redimensiona la imágen a 1/4 de su tamaño real
		$obj_simpleimage->save($destino_foto2_nuevo);											   // Guarda los cambios realizados	

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto2 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto2_nuevo, 79.7,  200, 60);	 								   // ... Agrega la imágen foto2 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto2_nuevo, 95,  191.3, 30);                                     // ... Agrega la imágen foto2 en el archivo pdf en forma vertical
		}

		$obj_simpleimage->load($destino_foto3);                                                    // Carga la imágen foto2
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4); // Redimensiona la imágen a 1/4 de su tamaño real
		$obj_simpleimage->save($destino_foto3_nuevo);                                              // Guarda los cambios realizados	
	 	
		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto3 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto3_nuevo, 144.4, 200, 60);	 								   // ... Agrega la imágen foto3 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto3_nuevo, 160, 191.3, 30);                                     // ... Agrega la imágen foto3 en el archivo pdf en forma vertical
		}
	}
	else if($foto1 && $foto2!=NULL)  // Si las variables $foto1 y $foto2 contienen imagenes, las dos imágenes se agregarán al archivo pdf
	{
		copy($ruta_foto1, $destino_foto1);
		copy($ruta_foto2, $destino_foto2);

		$obj_simpleimage->load($destino_foto1);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto1_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto1 es maá grande que el alto ... 
		{																						   
			$pdf->Image($destino_foto1_nuevo, 15.3,  200, 60); 									   // ... Agrega la foto1 en el archivo pdf en forma horizontal
		}					
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto1_nuevo, 30,  191.3, 30);                                     // ... Agrega la foto1 en el archivo pdf en forma vertical
		}

		$obj_simpleimage->load($destino_foto2);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto2_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto2 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto2_nuevo, 79.7,  200, 60);	 								   // ... Agrega la imágen foto2 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto2_nuevo, 95,  191.3, 30);                                     // ... Agrega la imágen foto2 en el archivo pdf en forma vertical
		}
	}
	else if($foto1 && $foto3!=NULL) // Si las variables $foto1 y $foto3 contienen imagenes, las dos imágenes se agregarán al archivo pdf
	{
		copy($ruta_foto1, $destino_foto1);
		copy($ruta_foto3, $destino_foto3);

		$obj_simpleimage->load($destino_foto1);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto1_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto1 es maá grande que el alto ... 
		{																						   
			$pdf->Image($destino_foto1_nuevo, 15.3,  200, 60); 									   // ... Agrega la foto1 en el archivo pdf en forma horizontal
		}					
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto1_nuevo, 30,  191.3, 30);                                     // ... Agrega la foto1 en el archivo pdf en forma vertical
		}

		$obj_simpleimage->load($destino_foto3);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto3_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto3 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto3_nuevo, 144.4, 200, 60);	 								   // ... Agrega la imágen foto3 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto3_nuevo, 160, 191.3, 30);                                     // ... Agrega la imágen foto3 en el archivo pdf en forma vertical
		}
	}
	else if($foto2 && $foto3!=NULL) // Si las variables $foto2 y $foto3 contienen imagenes, las dos imágenes se agregarán al archivo pdf
	{
		copy($ruta_foto2, $destino_foto2);
		copy($ruta_foto3, $destino_foto3);

		$obj_simpleimage->load($destino_foto2);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto2_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto2 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto2_nuevo, 79.7,  200, 60);	 								   // ... Agrega la imágen foto2 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto2_nuevo, 95,  191.3, 30);                                     // ... Agrega la imágen foto2 en el archivo pdf en forma vertical
		}

		$obj_simpleimage->load($destino_foto3);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto3_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto3 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto3_nuevo, 144.4, 200, 60);	 								   // ... Agrega la imágen foto3 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto3_nuevo, 160, 191.3, 30);                                     // ... Agrega la imágen foto3 en el archivo pdf en forma vertical
		}
	}
	else if($foto1!=NULL)
	{
		copy($ruta_foto1, $destino_foto1);

		$obj_simpleimage->load($destino_foto1);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto1_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto1 es maá grande que el alto ... 
		{																						   
			$pdf->Image($destino_foto1_nuevo, 15.3,  200, 60); 									   // ... Agrega la foto1 en el archivo pdf en forma horizontal
		}					
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto1_nuevo, 30,  191.3, 30);                                     // ... Agrega la foto1 en el archivo pdf en forma vertical
		}
	}
	else if($foto2!=NULL)
	{
		copy($ruta_foto2, $destino_foto2);

		$obj_simpleimage->load($destino_foto2);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto2_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto2 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto2_nuevo, 79.7,  200, 60);	 								   // ... Agrega la imágen foto2 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto2_nuevo, 95,  191.3, 30);                                     // ... Agrega la imágen foto2 en el archivo pdf en forma vertical
		}
	}
	else if($foto3!=NULL)
	{
		copy($ruta_foto3, $destino_foto3);
		
		$obj_simpleimage->load($destino_foto3);
		$obj_simpleimage->resize($obj_simpleimage->getWidth()/4, $obj_simpleimage->getHeight()/4);
		$obj_simpleimage->save($destino_foto3_nuevo);

		if($obj_simpleimage->getWidth()>$obj_simpleimage->getHeight())							   // Si el ancho de la foto3 es maá grande que el alto ... 
		{
			$pdf->Image($destino_foto3_nuevo, 144.4, 200, 60);	 								   // ... Agrega la imágen foto3 en el archivo pdf en forma horizontal
		}
		else                                                                                       // De no ser así ...
		{
			$pdf->Image($destino_foto3_nuevo, 160, 191.3, 30);                                     // ... Agrega la imágen foto3 en el archivo pdf en forma vertical
		}
	}
	
	/* Elimina las fotos del servidor */
	if ($foto1!=NULL) 
	{
		unlink($destino_foto1);
		unlink($destino_foto1_nuevo);

		if($foto2!=NULL)
		{
			unlink($destino_foto2);
			unlink($destino_foto2_nuevo);

			if($foto3!=NULL)
			{
				unlink($destino_foto3);
				unlink($destino_foto3_nuevo);
			}
		} 
	}
	else if ($foto2!=NULL) 
	{
		unlink($destino_foto2);
		unlink($destino_foto2_nuevo);

		if($foto3!=NULL)
		{
			unlink($destino_foto3);
			unlink($destino_foto3_nuevo);
		}
	}
	else if ($foto3!=NULL) 
	{
		unlink($destino_foto3);
		unlink($destino_foto3_nuevo);
	}

	/***************************************************************************/

	$pdf->SetXY(12.5, 251);
	$pdf->SetFillColor(255, 255, 255); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(195, 4, utf8_decode("2014 Visionaire Lighting. This document was created for the use of Visionaire Lighting and can be reproduced exclusively for those related to the company and under expressed written approval."), 0, 1, 'L');

	/***************************************************************************/

	$pdf->Output("../ncpr/$id_Folio.pdf", "F");  // Guarda el archivo pdf en la carpeta ncpr
	//$pdf->Output("../ncpr/$id_Folio.pdf", "I");  // Abre el archivo pdf en el navegador

	/***************************************************************************/

	echo "<script language='JavaScript'>
			window.alert('El NCPR ha sido creado.') 
			window.location.href='../mail.php?id_folio=$id_Folio'
			</script>";
?>