<?php
	define('FPDF_FONTPATH', 'fpdf/font/');
	require_once('fpdf/fpdf.php');
	include_once("DBManager.php");

	$objCon = new DBManager;

	class PDF extends FPDF
	{
		var $widths;
		var $aligns;

		function Header()
		{
			$this->SetFont('helvetica', '', 10);
			//$this->Text(20,14,'Historial clinico',0,'C', 0);
			$this->Ln(30);
		}

		function Footer()
		{
			$this->SetY(-20);
			$this->SetFont('helvetica', 'B', 8);
			//$this->Cell(100,10,'Historial medico',0,0,'L');
		}
	}

	/*$id_Folio=7;*/

	if ($objCon->conectar()==true)
	{
		
		/* Revisa en la base de datos la cantidad de registros de NCPR's */
		$sql0="SELECT COUNT(*) FROM tbncprs";
		$result0=mysql_query($sql0) or die;

		/* Al número obtenido, se le suma 1 y se le asigna al NCPR */
		$id_Folio=(mysql_result($result0, 0));

		$sql="SELECT * FROM tbncprs WHERE id_Folio='$id_Folio'";
		$result = mysql_query($sql);
		
		while ($row=mysql_fetch_array($result)) 
		{ 
			$ORDEN=$row['Numero_Orden'];
			$PARTE=$row['Numero_Parte'];
			$TURNO=$row['Turno'];
			$FECHAENVIO=$row['Fecha_Envio'];
			$DESCRIPCIONPARTE=$row['Descripcion_Producto'];
			$PROVEEDOR=$row['Nombre_Proveedor'];
			$REPORTA=$row['Reportado_Por'];
			$GENERA=$row['Generado_Por'];
			$FECHA=$row['Fecha'];
			$HORA=$row['Hora'];
			$area_falla_detectada=$row['Origen_Falla_Detectada'];
			$LOCALIZADEFECTO=$row['Origen_Falla_Detectada'];
			$LOCALIZADEFECTODESC=$row['Origen_Falla_Descripcion'];
			$LOCACIONDEFECTO=$row['Locacion_Falla'];
			$LOCACIONDEFECTODESC=$row['Locacion_Falla_Desc'];
			$PIEZASORDEN=$row['Numero_Piezas'];
			$PIEZASRECHAZADAS=$row['Numero_Piezas_Rechazadas'];
			$RECHAZO=$row['Razon_Rechazo'];
			$DESCRIPCIONFALLA=$row['Descripcion'];
			$DISPOSICION=$row['Disposicion_Producto'];
			$DISPOSICIONDESCRIPCION=$row['Disposicion_Producto_Desc'];
			$RECHAZODESCRIPCION=$row['Razon_Rechazo_Desc'];	
			$DETECCION=$row["Area_Dept_Codigo"];
			$DETECCIONDESCRIPCION=$row["Area_Dept_Desc"];
		}
	}
	
	$DISPOSICIONPD=$DISPOSICION .' - '. $DISPOSICIONDESCRIPCION;
	$LOCALIZADD=$LOCALIZADEFECTO .' - '. $LOCALIZADEFECTODESC;
	$LOCACIONFD=$LOCACIONDEFECTO .' - '. $LOCACIONDEFECTODESC;
	$RECHAZOD=$RECHAZO .' - '. $RECHAZODESCRIPCION;
	$DETEC=$DETECCION .' - '. $DETECCIONDESCRIPCION;

	/* Declaración de variables */
	//$folio=$_POST['id_folio'];Generado por (Generated by):
	$documento_no="VL-PA-SGC-001-F02";
	$pagina="1 OF 1";
	$document="NON-CONFORMING PRODUCT REPORT";
	$revision="4";
	$fecha=$FECHA;
	$nombre_documento="NON-CONFORMING PRODUCT REPORT (ENGLISH)";
	
	//$foto1="img/foto1.jpg";
	//$foto2="img/foto2.jpg";Generado por (Generated by):
	//$foto3="img/foto3.jpg";
	/* Fin de declaración de variables */

	/* Variables del sistema*/
	$setx=13;
	$cellx=45;
	$cellsize=194;
	$setderecha=99;
	/* Fin de variables del sistema*/

	// PDF(Vertical, Milimetros, Tamaño Carta)
	$pdf=new PDF('P', 'mm', 'Letter');
	$pdf->AddPage();
	$pdf->SetFont('helvetica', '', '8');
	
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(11, 13, 198, 235);   // Contenedor principal
	
	$pdf->Image('./img/Logo.jpg', 27, 17, 65); //Imagen de logotipo
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 15, 97, 15);    // Recuadro del Logo

	$pdf->SetXY(110, 19);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell(63, 5, "DOCUMENTO NO.:", 0, 1, 'C', 'F');

	$pdf->SetXY(110, 24);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(63, 5, $documento_no, 0, 1, 'C');

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(110, 15, 63, 15);

	/***************************************************************************/
	
	$pdf->SetXY(173, 19);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->cell(34, 5, "PAGINA:", 0, 1, 'C');

	$pdf->SetXY(173, 24);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(34, 5, $pagina, 0, 1, 'C');

	$pdf->SetXY(115, 580);
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(173, 15, 34, 15);

	/***************************************************************************/

	$pdf->SetXY($setx, 31.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->cell(19, 5, "DOCUMENT:", 0, 1, 'L');

	$pdf->SetXY($setx+19, 31.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(60, 5, $document, 0, 1, 'L');

	$pdf->SetXY($setx, 35.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->Cell(16, 5, "REVISION:", 0, 1, 'L');

	$pdf->SetXY($setx+16, 35.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(63, 5, $revision, 0, 1, 'L');

	$pdf->SetXY($setx, 39.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->Cell(12, 5, "FECHA:", 0, 1, 'L');

	$pdf->SetXY($setx+12, 39.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(66, 5, $fecha, 0, 1, 'L');
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 30, 97, 15);    // DOCUMENT

	/***************************************************************************/

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->SetXY(110, 31.5);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->Cell(97, 5, "NOMBRE DEL DOCUMENTO:", 0, 1, 'C');

	$pdf->SetXY(110, 35.5);
	$pdf->SetFont('Arial', '', '8');
	$pdf->Cell(97, 5, $nombre_documento, 0, 1, 'C');

	$pdf->Rect(110, 30, $setderecha-2, 15);    // NOMBRE DEL DOCUMENTO

	/***************************************************************************/

	$pdf->SetXY(110, 50);
	$pdf->SetFont('Arial', 'B', '8');
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	// C (El texto de la celda lo envia al centro), F (Rellena la celda con el color seleccionado)
	$pdf->Cell(63, 5, "Folio No. (File No.):", 1, 1, 'C', 'C');

	$pdf->SetXY(173, 50);
	$pdf->SetFont('Arial', '', '8');
	$pdf->SetTextColor(51, 51, 153); // Color Morado
	$pdf->Cell(34, 5, '', 1, 1, 'C');

	/***************************************************************************/

	$pdf->SetXY($setx, 55);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("(1) Información general del reporte (General Information of the report)"), 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 60);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Multicell($cellx+6, 10, "Reportado por (Reported by):", 1, 1, 'L', 'F');
	
	$pdf->SetXY(64, 60);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->Cell(46, 10, '', 1, 1, 'C', 'F');
	 
	$pdf->SetXY(110, 60);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell(47, 10, "Generado por (Generated by):", 1, 1, 'C', 'F');

	$pdf->SetXY(155, 60);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->Cell(52, 10, '', 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 70);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell($cellx+6, 10, utf8_decode("Área/Department (Detected On):"), 1, 1, 'L', 'F');
	
	$pdf->SetXY(65, 70.5);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->SetFont('Arial', '', '7');
	$pdf->Multicell(44, 3, '', 0, 1, 'C', 'F');

	$pdf->SetXY(110, 70);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFont('Arial', '', '8');
	$pdf->Multicell(45, 10, utf8_decode("Área/Department (Origin defect):"), 1, 1, 'L', 'F');

	$pdf->SetXY(156, 70.5);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->SetFont('Arial', '', '7');
	$pdf->Multicell(50, 3, '', 0, 1, 'C', 'F');

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(155, 70, 52, 10);    // $LOCALIZADD

	/***************************************************************************/
	
	$pdf->SetXY($setx, 80);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFont('Arial', '', '8');
	$pdf->cell($cellx+6, 5, "Fecha (Date):", 1, 1, 'L', 'F');

	$pdf->SetXY(64, 80);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(22, 5, '', 1, 1, 'C', 'F');

	$pdf->SetXY(86, 80);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell(24, 5, "Hora (Time):", 1, 1, 'L', 'F');

	$pdf->SetXY(110, 80);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(22, 5, '', 1, 1, 'C', 'F');

	$pdf->SetXY(132, 80);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell(23, 5, "Turno (Shift):", 1, 1, 'L', 'F');

	$pdf->SetXY(155, 80);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(52, 5, '', 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 85);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell(51, 5, utf8_decode("Número de Job (Job Number)"), 1, 1, 'L', 'F');

	$pdf->SetXY(64, 85);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(46, 5, '', 1, 1, 'C', 'F');

	$pdf->SetXY(110, 85);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell($cellx+2, 5, "Fecha de Envio (Shipping date):", 1, 1, 'L', 'F');

	$pdf->SetXY(155, 85);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(52, 5, '', 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 90);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->cell($cellx+6, 5, "No. De Parte (Part No.):", 1, 1, 'L', 'F');

	$pdf->SetXY(64, 90);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(143, 5, '', 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 95);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell($cellx+6, 5, utf8_decode("Descripción del producto o la parte (Product/Part description):"), 1, 1, 'L', 'F');

	$pdf->SetXY(64, 95);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(143, 10, '', 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 105);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell($cellx+6, 10, "Nombre del proveedor (Vendor name):", 1, 1, 'L', 'F');

	$pdf->SetXY(64, 105);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(143, 10, '', 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 115);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell(73, 10, "No. de piezas en el job (No. of pieces in the job):", 1, 1, 'L', 'F');

	$pdf->SetXY(86, 115);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(24, 10, '', 1, 1, 'C', 'F');

	$pdf->SetXY(110, 115);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->Multicell(65, 5, "No. de piezas rechazadas (No. of pieces rejected):", 1, 1, 'L', 'F');

	$pdf->SetXY(173, 115);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->cell(34, 10, '', 1, 1, 'C', 'F');

	/***************************************************************************/
	
	$pdf->SetXY($setx, 125);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("(2) Razón de rechazo (Reason for rejection)"), 1, 1, 'C', 'F');

	/***************************************************************************/
	
	$pdf->SetXY($setx, 130);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->cell($cellsize, 10, '', 1, 1, 'C', 'F');	
		
	/***************************************************************************/
	
	$pdf->SetXY($setx, 140);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("(3) Descripción de la no-conformidad (DESCRIPTION OF THE NON-CONFORMANCE)"), 1, 1, 'C', 'F');

	/***************************************************************************/
	
	$pdf->SetXY($setx+1, 146);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	$pdf->Multicell(191, 4, '', 0, 1, 'C', 'F');	
	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 145, $cellsize, 20); // (3) Descripción  
	
	/***************************************************************************/
	
	$pdf->SetXY($setx, 165);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect(110, 165.1, $setderecha-2, 10, 'F'); // (5) Disposición del producto

	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell(97, 10, utf8_decode("(4) Localización del defecto (Detected on)"), 1, 1, 'C', 'F');

	$pdf->SetXY(111, 166);
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(95, 4, utf8_decode("(5) Disposición del producto no conforme (Disposition of non-conformance product)"), 0, 1, 'C');

	/***************************************************************************/

	$pdf->SetXY($setx+1, 176);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	$pdf->SetFillColor(255, 255, 255); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(95, 3.5, '', 0, 1, 'C', 'F');

	$pdf->SetXY(111, 176);
	$pdf->SetTextColor(31, 73, 125); // Color Azul
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(95, 3.5, '', 0, 1, 'C', 'F');

	//Rect(Izquierda, Arriba, Derecha, Abajo)
	$pdf->Rect($setx, 175, $setderecha-2, 10); // (4) Localización del defecto*/
	$pdf->Rect(110, 175, $setderecha-2, 10); // (5) Disposición del producto  
	$pdf->Rect(110, 165, $setderecha-2, 10); // $DISPOSICIONPD  

	/***************************************************************************/

	$pdf->SetXY($setx, 185);
	$pdf->SetTextColor(0, 0, 0); // Color Negro
	$pdf->SetFillColor(141, 180, 226); // Color Azul
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Cell($cellsize, 5, utf8_decode("Archivo fotográfico (Photo archive)"), 1, 1, 'C', 'F');

	/***************************************************************************/

	$pdf->SetXY($setx, 190);
	$pdf->SetFillColor(255, 255, 255); // Color Blanco
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(64.6, 56, utf8_decode(""), 1, 1, 'C');

	$pdf->SetXY($setx+64.6, 190);
	// C (Centra el texto de la celda)
	$pdf->Multicell(64.6, 56, utf8_decode(""), 1, 1, 'C');

	$pdf->SetXY($setx+129, 190);
	// C (Centra el texto de la celda)
	$pdf->Multicell(65, 56, utf8_decode(""), 1, 1, 'C');

    /***************************************************************************/
	
	//$pdf->Image($foto1, 14.5, 200, 60); //Imagen de logotipo
	//$pdf->Image($foto2, 78, 200, 60); //Imagen de logotipo
	//$pdf->Image($foto3, 141.5, 200, 60); //Imagen de logotipo

	/***************************************************************************/
	
	$pdf->SetXY(12.5, 251);
	$pdf->SetFillColor(255, 255, 255); // Color Gris
	// C (Centra el texto de la celda), F (Rellena la celda con el color seleccionado)
	$pdf->Multicell(195, 4, utf8_decode("2016 Visionaire Lighting. This document was created for the use of Visionaire Lighting and can be reproduced exclusively for those related to the company and under expressed written approval."), 0, 1, 'L');

	/***************************************************************************/

$pdf->Output("ncpr/$id_Folio.pdf", "F");
$pdf->Output("ncpr/$id_Folio.pdf", "I");
?>